# Generated by Django 5.2.1 on 2025-07-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_email_dueno_alter_mascota_rut_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='telefono_dueno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
