# Generated by Django 5.2.4 on 2025-07-16 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_alter_mascota_telefono_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='telefono_dueno',
            field=models.CharField(blank=True, help_text='Formato: +56912345678 o 912345678', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono chileno válido (ej: +56912345678 o 912345678)', regex='^(\\+56)?9[0-9]{8}$')]),
        ),
    ]
