# Generated by Django 5.2.4 on 2025-07-16 05:45

import mascotas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_telefono_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='rut_dueno',
            field=models.CharField(help_text='Formato: 12345678-9 o 12.345.678-9', max_length=12, validators=[mascotas.models.validar_rut_chileno], verbose_name='RUT del dueño'),
        ),
    ]
