# Generated by Django 5.2.1 on 2025-07-16 06:07

import mascotas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_alter_mascota_rut_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='email_dueno',
            field=models.EmailField(help_text='Formato: ejemplo@gmail.com', max_length=254, validators=[mascotas.models.validar_email_chileno], verbose_name='Correo del dueño'),
        ),
    ]
